// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.0
// source: blackboard.proto

package blackboard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_UNSPECIFIED  MessageType = 0
	MessageType_SENSOR_VALUE MessageType = 1
	MessageType_STATUS       MessageType = 2
	MessageType_ALARM        MessageType = 3
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "SENSOR_VALUE",
		2: "STATUS",
		3: "ALARM",
	}
	MessageType_value = map[string]int32{
		"UNSPECIFIED":  0,
		"SENSOR_VALUE": 1,
		"STATUS":       2,
		"ALARM":        3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_blackboard_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_blackboard_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_blackboard_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_OFFLINE       Status = 0
	Status_ONLINE        Status = 1
	Status_UPDATING      Status = 2
	Status_CRITICALERROR Status = 3
	Status_PARTIALOUTAGE Status = 4
	Status_MAINTENANCE   Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OFFLINE",
		1: "ONLINE",
		2: "UPDATING",
		3: "CRITICALERROR",
		4: "PARTIALOUTAGE",
		5: "MAINTENANCE",
	}
	Status_value = map[string]int32{
		"OFFLINE":       0,
		"ONLINE":        1,
		"UPDATING":      2,
		"CRITICALERROR": 3,
		"PARTIALOUTAGE": 4,
		"MAINTENANCE":   5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_blackboard_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_blackboard_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_blackboard_proto_rawDescGZIP(), []int{1}
}

type Load int32

const (
	Load_LOW    Load = 0
	Load_MEDIUM Load = 1
	Load_MIGH   Load = 2
)

// Enum value maps for Load.
var (
	Load_name = map[int32]string{
		0: "LOW",
		1: "MEDIUM",
		2: "MIGH",
	}
	Load_value = map[string]int32{
		"LOW":    0,
		"MEDIUM": 1,
		"MIGH":   2,
	}
)

func (x Load) Enum() *Load {
	p := new(Load)
	*p = x
	return p
}

func (x Load) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Load) Descriptor() protoreflect.EnumDescriptor {
	return file_blackboard_proto_enumTypes[2].Descriptor()
}

func (Load) Type() protoreflect.EnumType {
	return &file_blackboard_proto_enumTypes[2]
}

func (x Load) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Load.Descriptor instead.
func (Load) EnumDescriptor() ([]byte, []int) {
	return file_blackboard_proto_rawDescGZIP(), []int{2}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderID    string      `protobuf:"bytes,1,opt,name=senderID,proto3" json:"senderID,omitempty"`
	MessageType MessageType `protobuf:"varint,2,opt,name=messageType,proto3,enum=blackboard.MessageType" json:"messageType,omitempty"`
	Content     string      `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blackboard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_blackboard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_blackboard_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetSenderID() string {
	if x != nil {
		return x.SenderID
	}
	return ""
}

func (x *Message) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_UNSPECIFIED
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type WriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blackboard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blackboard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_blackboard_proto_rawDescGZIP(), []int{1}
}

func (x *WriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StatusMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceID string `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Status   Status `protobuf:"varint,2,opt,name=status,proto3,enum=blackboard.Status" json:"status,omitempty"`
	Load     Load   `protobuf:"varint,3,opt,name=load,proto3,enum=blackboard.Load" json:"load,omitempty"`
	Info     string `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *StatusMessage) Reset() {
	*x = StatusMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blackboard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusMessage) ProtoMessage() {}

func (x *StatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_blackboard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusMessage.ProtoReflect.Descriptor instead.
func (*StatusMessage) Descriptor() ([]byte, []int) {
	return file_blackboard_proto_rawDescGZIP(), []int{2}
}

func (x *StatusMessage) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *StatusMessage) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OFFLINE
}

func (x *StatusMessage) GetLoad() Load {
	if x != nil {
		return x.Load
	}
	return Load_LOW
}

func (x *StatusMessage) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type ConfigMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigID   string `protobuf:"bytes,1,opt,name=configID,proto3" json:"configID,omitempty"`
	ConfigJSON string `protobuf:"bytes,2,opt,name=configJSON,proto3" json:"configJSON,omitempty"`
}

func (x *ConfigMessage) Reset() {
	*x = ConfigMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blackboard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMessage) ProtoMessage() {}

func (x *ConfigMessage) ProtoReflect() protoreflect.Message {
	mi := &file_blackboard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMessage.ProtoReflect.Descriptor instead.
func (*ConfigMessage) Descriptor() ([]byte, []int) {
	return file_blackboard_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigMessage) GetConfigID() string {
	if x != nil {
		return x.ConfigID
	}
	return ""
}

func (x *ConfigMessage) GetConfigJSON() string {
	if x != nil {
		return x.ConfigJSON
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blackboard_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_blackboard_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_blackboard_proto_rawDescGZIP(), []int{4}
}

var File_blackboard_proto protoreflect.FileDescriptor

var file_blackboard_proto_rawDesc = []byte{
	0x0a, 0x10, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x22, 0x7a,
	0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x39, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x62, 0x6c, 0x61,
	0x63, 0x6b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x29, 0x0a, 0x0d, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x91, 0x01, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x44, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x24, 0x0a, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x62, 0x6c, 0x61, 0x63, 0x6b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x52,
	0x04, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x4b, 0x0a, 0x0d, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x4a, 0x53, 0x4f, 0x4e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x4a, 0x53, 0x4f, 0x4e, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x2a,
	0x47, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f,
	0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x10, 0x0a, 0x0c, 0x53, 0x45, 0x4e, 0x53, 0x4f, 0x52, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x10, 0x02, 0x12, 0x09, 0x0a,
	0x05, 0x41, 0x4c, 0x41, 0x52, 0x4d, 0x10, 0x03, 0x2a, 0x66, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x46, 0x46, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x4f, 0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x55,
	0x50, 0x44, 0x41, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x52, 0x49,
	0x54, 0x49, 0x43, 0x41, 0x4c, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d,
	0x50, 0x41, 0x52, 0x54, 0x49, 0x41, 0x4c, 0x4f, 0x55, 0x54, 0x41, 0x47, 0x45, 0x10, 0x04, 0x12,
	0x0f, 0x0a, 0x0b, 0x4d, 0x41, 0x49, 0x4e, 0x54, 0x45, 0x4e, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x05,
	0x2a, 0x25, 0x0a, 0x04, 0x4c, 0x6f, 0x61, 0x64, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x4f, 0x57, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x45, 0x44, 0x49, 0x55, 0x4d, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x4d, 0x49, 0x47, 0x48, 0x10, 0x02, 0x32, 0xc7, 0x02, 0x0a, 0x11, 0x42, 0x6c, 0x61, 0x63,
	0x6b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a,
	0x0c, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x13, 0x2e,
	0x62, 0x6c, 0x61, 0x63, 0x6b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x1a, 0x19, 0x2e, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a,
	0x0c, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x11, 0x2e,
	0x62, 0x6c, 0x61, 0x63, 0x6b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x13, 0x2e, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x30, 0x01, 0x12, 0x37, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x13, 0x2e, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x13, 0x2e, 0x62, 0x6c,
	0x61, 0x63, 0x6b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x39, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x11, 0x2e,
	0x62, 0x6c, 0x61, 0x63, 0x6b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x19, 0x2e, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x44, 0x0a, 0x0c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x19, 0x2e, 0x62, 0x6c,
	0x61, 0x63, 0x6b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x19, 0x2e, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blackboard_proto_rawDescOnce sync.Once
	file_blackboard_proto_rawDescData = file_blackboard_proto_rawDesc
)

func file_blackboard_proto_rawDescGZIP() []byte {
	file_blackboard_proto_rawDescOnce.Do(func() {
		file_blackboard_proto_rawDescData = protoimpl.X.CompressGZIP(file_blackboard_proto_rawDescData)
	})
	return file_blackboard_proto_rawDescData
}

var file_blackboard_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_blackboard_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_blackboard_proto_goTypes = []interface{}{
	(MessageType)(0),      // 0: blackboard.MessageType
	(Status)(0),           // 1: blackboard.Status
	(Load)(0),             // 2: blackboard.Load
	(*Message)(nil),       // 3: blackboard.Message
	(*WriteResponse)(nil), // 4: blackboard.WriteResponse
	(*StatusMessage)(nil), // 5: blackboard.StatusMessage
	(*ConfigMessage)(nil), // 6: blackboard.ConfigMessage
	(*Empty)(nil),         // 7: blackboard.Empty
}
var file_blackboard_proto_depIdxs = []int32{
	0, // 0: blackboard.Message.messageType:type_name -> blackboard.MessageType
	1, // 1: blackboard.StatusMessage.status:type_name -> blackboard.Status
	2, // 2: blackboard.StatusMessage.load:type_name -> blackboard.Load
	3, // 3: blackboard.BlackboardService.WriteMessage:input_type -> blackboard.Message
	7, // 4: blackboard.BlackboardService.ReadMessages:input_type -> blackboard.Empty
	3, // 5: blackboard.BlackboardService.ReadMessage:input_type -> blackboard.Message
	7, // 6: blackboard.BlackboardService.GetStatus:input_type -> blackboard.Empty
	6, // 7: blackboard.BlackboardService.UpdateConfig:input_type -> blackboard.ConfigMessage
	4, // 8: blackboard.BlackboardService.WriteMessage:output_type -> blackboard.WriteResponse
	3, // 9: blackboard.BlackboardService.ReadMessages:output_type -> blackboard.Message
	3, // 10: blackboard.BlackboardService.ReadMessage:output_type -> blackboard.Message
	5, // 11: blackboard.BlackboardService.GetStatus:output_type -> blackboard.StatusMessage
	4, // 12: blackboard.BlackboardService.UpdateConfig:output_type -> blackboard.WriteResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_blackboard_proto_init() }
func file_blackboard_proto_init() {
	if File_blackboard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_blackboard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blackboard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blackboard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blackboard_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blackboard_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blackboard_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blackboard_proto_goTypes,
		DependencyIndexes: file_blackboard_proto_depIdxs,
		EnumInfos:         file_blackboard_proto_enumTypes,
		MessageInfos:      file_blackboard_proto_msgTypes,
	}.Build()
	File_blackboard_proto = out.File
	file_blackboard_proto_rawDesc = nil
	file_blackboard_proto_goTypes = nil
	file_blackboard_proto_depIdxs = nil
}
